version: "3"

services:
  php:
    build: php
    networks: [php-app]
    restart: always
    depends_on: [db]
    ports: ["5010:80"]
    environment:
      NATAS06: gopher{15384ec648c6f3bc335cd959877e01f5}
    volumes:
      - ./php:/var/www/html:ro

  db:
    build: mysql-init
    networks: [php-app]
    restart: always
    expose: [3306]
    ports: []
    environment:
      MARIADB_ROOT_PASSWORD: 0127357d4b5bf09a1c6f856ae39ef44b
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

networks:
  php-app:
